# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, mkdocs, debug_mkdocs_failure ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install Pip
      run:  python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install mkdocs && pip install mkdocs-material markdown-include

    - name: Build docs
      run:  python -m mkdocs build

    - name: Deploy MkDocs
      # See: https://github.com/mhausenblas/mkdocs-deploy-gh-pages/pull/74
      uses: mhausenblas/mkdocs-deploy-gh-pages@9ed3b4354aa821831ba17a63c55caf73b23e6109
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Note: container is Alpine Linux so package names must match!
        EXTRA_PACKAGES: "gcc libxml2-dev libxslt-dev musl-dev"
